# Development Dockerfile with hot reload
FROM node:22.12.0-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

RUN yarn install

COPY prisma ./prisma
RUN yarn prisma:generate

COPY tsconfig.json ./
COPY src ./src

EXPOSE 3000

CMD ["yarn", "dev"]
